Fix minimum `typer` version. lock with poetry.
Typer was throwing an error with old versions:
TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'